plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrdalse2.sbsplusproxy'
    compileSdk 36

    defaultConfig {
        applicationId 'com.mrdalse2.sbsplusproxy'
        minSdk 26
        targetSdk 35
        versionCode 99
        versionName '1.0.302-test'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
